### PR TITLE
Delete New.txt File

### PR DESCRIPTION
**Pull request by Abdul-Sami9678**
Deleted this file immediately!

Harmful Caution.....
Please..............

### CODE REVIEW

**Review by SamiKhan8920 — COMMENTED** [review]
Why?

**Comment by Abdul-Sami9678** [comment]
PLease....

**Comment by SamiKhan8920** [comment]
Give me main reason....

**Comment by Abdul-Sami9678** [comment]
Sir it's Urgent......

**Review by SamiKhan8920 — APPROVED** [review]
Okay!

My son enjoy the party............

**Pull request merged**
